import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html className="bg-background h-full min-h-screen w-full">
      <Head>
        <link rel="icon" href="/layout-kanban.svg" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
