export const colors = {
  SLATE: "#25262b",
  GRAY: "#868e96",
  RED: "#fa5252",
  PINK: "#e64980",
  PURPLE: "#be4bdb",
  VIOLET: "#7950f2",
  DARKBLUE: "#4c6ef5",
  BLUE: "#228be6",
  TURQUOISE: "#15aabf",
  OCEAN: "#12b886",
  GREEN: "#40c057",
  LIGHTGREEN: "#82c91e",
  YELLOW: "#fab005",
  ORANGE: "#fd7e14",
} as const;
export const colorTranslations = {
  SLATE: "Koyu Gri",
  GRAY: "Gri",
  RED: "Kırmızı",
  PINK: "Pembe",
  PURPLE: "Mor",
  VIOLET: "Menekşe",
  DARKBLUE: "Koyu Mavi",
  BLUE: "Mavi",
  TURQUOISE: "Turkuaz",
  OCEAN: "Deniz Mavisi",
  GREEN: "Yeşil",
  LIGHTGREEN: "Açık Yeşil",
  YELLOW: "Sarı",
  ORANGE: "Turuncu",
} as const;
